package html.dsl

import html.Attribute

object Attributes {
  class TagAttribute(name: String) {
    def := (value: String): Attribute = Attribute(name, value)
  }

  val accept = new TagAttribute("accept")
  val acceptCharset = new TagAttribute("accept-charset")
  val accesskey = new TagAttribute("accesskey")
  val action = new TagAttribute("action")
  val alt = new TagAttribute("alt")
  val autocomplete = new TagAttribute("autocomplete")
  val autofocus = new TagAttribute("autofocus")
  val autoplay = new TagAttribute("autoplay")
  val checked = new TagAttribute("checked")
  val cite = new TagAttribute("cite")
  val `class` = new TagAttribute("class")
  val cols = new TagAttribute("cols")
  val colspan = new TagAttribute("colspan")
  val contenteditable = new TagAttribute("contenteditable")
  val controls = new TagAttribute("controls")
  val coords = new TagAttribute("coords")
  val data = new TagAttribute("data")
  val datetime = new TagAttribute("datetime")
  val default = new TagAttribute("default")
  val dir = new TagAttribute("dir")
  val dirname = new TagAttribute("dirname")
  val disabled = new TagAttribute("disabled")
  val download = new TagAttribute("download")
  val draggable = new TagAttribute("draggable")
  val dropzone = new TagAttribute("dropzone")
  val enctype = new TagAttribute("enctype")
  val `for` = new TagAttribute("for")
  val form = new TagAttribute("form")
  val formaction = new TagAttribute("formaction")
  val headers = new TagAttribute("headers")
  val height = new TagAttribute("height")
  val hidden = new TagAttribute("hidden")
  val high = new TagAttribute("high")
  val href = new TagAttribute("href")
  val hreflang = new TagAttribute("hreflang")
  val id = new TagAttribute("id")
  val ismap = new TagAttribute("ismap")
  val kind = new TagAttribute("kind")
  val label = new TagAttribute("label")
  val lang = new TagAttribute("lang")
  val list = new TagAttribute("list")
  val loop = new TagAttribute("loop")
  val low = new TagAttribute("low")
  val max = new TagAttribute("max")
  val maxlength = new TagAttribute("maxlength")
  val media = new TagAttribute("media")
  val method = new TagAttribute("method")
  val min = new TagAttribute("min")
  val multiple = new TagAttribute("multiple")
  val muted = new TagAttribute("muted")
  val name = new TagAttribute("name")
  val novalidate = new TagAttribute("novalidate")
  val open = new TagAttribute("open")
  val optimum = new TagAttribute("optimum")
  val pattern = new TagAttribute("pattern")
  val placeholder = new TagAttribute("placeholder")
  val poster = new TagAttribute("poster")
  val preload = new TagAttribute("preload")
  val readonly = new TagAttribute("readonly")
  val rel = new TagAttribute("rel")
  val required = new TagAttribute("required")
  val reversed = new TagAttribute("reversed")
  val rows = new TagAttribute("rows")
  val rowspan = new TagAttribute("rowspan")
  val sandbox = new TagAttribute("sandbox")
  val scope = new TagAttribute("scope")
  val selected = new TagAttribute("selected")
  val shape = new TagAttribute("shape")
  val size = new TagAttribute("size")
  val sizes = new TagAttribute("sizes")
  val span = new TagAttribute("span")
  val spellcheck = new TagAttribute("spellcheck")
  val src = new TagAttribute("src")
  val srcdoc = new TagAttribute("srcdoc")
  val srclang = new TagAttribute("srclang")
  val srcset = new TagAttribute("srcset")
  val start = new TagAttribute("start")
  val step = new TagAttribute("step")
  val style = new TagAttribute("style")
  val tabindex = new TagAttribute("tabindex")
  val target = new TagAttribute("target")
  val title = new TagAttribute("title")
  val translate = new TagAttribute("translate")
  val `type` = new TagAttribute("type")
  val usemap = new TagAttribute("usemap")
  val value = new TagAttribute("value")
  val width = new TagAttribute("width")
  val wrap = new TagAttribute("wrap")
}
