version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: cat /dev/null | sbt server/test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: cat /dev/null | sbt server/test:test
  int_test:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mongo:latest
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: cat /dev/null | sbt server/it:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run:
          name: Run server
          background: true
          command: cat /dev/null | sbt run
          environment:
            MONGO_URL: mongodb://127.0.0.1:27017
            PORT: 8080
      - run:
          name: Run integration tests
          command: |
            dockerize -wait tcp://$SERVER_URL -timeout 1m
            cat /dev/null | sbt server/it:test
          environment:
            SERVER_URL: localhost
            SERVER_PORT: 8080

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - int_test:
          requires:
            - build